/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Test2ndAutoConfigView.java
 *
 * Created on 01-ene-2006, 0:20:48
 */
package quino.view.test2nd;

import quino.clases.config.ConfigEnsayoEnrejadoAuto;
import quino.clases.config.ConfigEnsayoGaborAuto;
import quino.clases.config.ConfigEnsayoOrientacionAuto;
import quino.clases.config.ConfigEnsayoShapeDetectAuto;
import quino.clases.config.ConfigEnsayoVelocidad;
import quino.clases.config.ConfigEnsayoVelocidadAuto;
import quino.util.test.Prueba;
import quino.util.test.PruebaEnrejado;
import quino.util.test.PruebaGabor;
import quino.util.test.PruebaOrientacion;
import quino.util.test.PruebaShape;
import quino.util.test.PruebaVelocidad;
import quino.view.main.ErrorDialog;
import quino.view.main.PrincipalView;

/**
 *
 * @author Administrador
 */
public class AutoTest2ndConfigView extends javax.swing.JDialog {

    private PrincipalView parent;

    /** Creates new form Test2ndAutoConfigView */
    public AutoTest2ndConfigView(PrincipalView parent, boolean modal) {
        super(parent, modal);

        initComponents();
        this.parent = parent;
        setLocationRelativeTo(null);

        if (parent.getConf() instanceof ConfigEnsayoShapeDetectAuto) {
            jLabel7.setText(jLabel7.getText() + "Detección de Forma");
        } else if (parent.getConf() instanceof ConfigEnsayoVelocidad) {
            jLabel7.setText(jLabel7.getText() + "Detección de Velocidad");
        } else if (parent.getConf() instanceof ConfigEnsayoEnrejadoAuto) {
            jLabel7.setText(jLabel7.getText() + "Enrejado");
        } else if (parent.getConf() instanceof ConfigEnsayoGaborAuto) {
            jLabel7.setText(jLabel7.getText() + "Campana de Gabor");
        } else if (parent.getConf() instanceof ConfigEnsayoOrientacionAuto) {
            jLabel7.setText(jLabel7.getText() + "Detección de Orientación");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" Configuración automática");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad de ensayos");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSpinner1.setValue(1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(0, 21, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int cantEnsayos = 0;
            try {
                cantEnsayos = Integer.parseInt(String.valueOf(jSpinner1.getValue()));
            } catch (Exception e) {
                throw new Exception("La cantidad de ensayos debe ser un número entero");
            }
            if (parent.getConf() instanceof ConfigEnsayoShapeDetectAuto) {
                Prueba prueba = new PruebaShape((ConfigEnsayoShapeDetectAuto) parent.getConf(), cantEnsayos);
                parent.setPrueba(prueba);
                ShapeDetectTestView sdtv = new ShapeDetectTestView(parent, true, false);
                sdtv.setVisible(true);
            } else if (parent.getConf() instanceof ConfigEnsayoVelocidadAuto) {
                Prueba prueba = new PruebaVelocidad((ConfigEnsayoVelocidadAuto) parent.getConf(), cantEnsayos);
                parent.setPrueba(prueba);
                VelocidadTestView vtv = new VelocidadTestView(parent, true, false);
                vtv.setVisible(true);
            } else if (parent.getConf() instanceof ConfigEnsayoEnrejadoAuto) {
                Prueba prueba = new PruebaEnrejado((ConfigEnsayoEnrejadoAuto) parent.getConf(), cantEnsayos);
                parent.setPrueba(prueba);
                EnrejadoTestView etv = new EnrejadoTestView(parent, true, false);
                etv.setVisible(true);
            } else if (parent.getConf() instanceof ConfigEnsayoGaborAuto) {
                Prueba prueba = new PruebaGabor((ConfigEnsayoGaborAuto) parent.getConf(), cantEnsayos);
                parent.setPrueba(prueba);
                GaborTestView gtv = new GaborTestView(parent, true, false);
                gtv.setVisible(true);
            } else if (parent.getConf() instanceof ConfigEnsayoOrientacionAuto) {
                Prueba prueba = new PruebaOrientacion((ConfigEnsayoOrientacionAuto) parent.getConf(), cantEnsayos);
                parent.setPrueba(prueba);
                OrientacionTestView otv = new OrientacionTestView(parent, true, false);
                otv.setVisible(true);
            }
            setVisible(false);
            dispose();
        } catch (Exception exception) {
            ErrorDialog err = new ErrorDialog(parent, true, exception.getMessage());
            err.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AutoTest2ndConfigView dialog = new AutoTest2ndConfigView(new PrincipalView(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
